### ISSUE TITLE
Too large compile error message causes a TransactionTooLargeException

### ISSUE THREAD

**Issue by mikothedev** [Sketchware-Pro/Sketchware-Pro#1043]
**Describe the bug**
when compiling the project it will shows an error "TransactionTooLargeException" 

**Expected behavior**
that's it it show error and sometimes kicking me out of my screen and the sketchware will reload itself.

**Screenshots**
no screenshot because it is kicking me out when viewing the error i only know the error because of dialogue error.

Device and Sketchware Pro-related info:
 - Device: [oppo a16k]
 - OS: [Android 11]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**
I can't compile the application

**Comment by JavkhlanK** [comment]
Please specify the used Sketchware Pro version the next time, don't leave the example from the template.

This only happens when the error message is pretty large. The last compile error is also written to /Internal storage/.sketchware/data/&lt;project ID&gt;/compile_log, so open that file with a file manager and fix your project's problems in the meantime.

**Comment by mikothedev** [comment]
I apologize for my behavior.

what do you mean by "message is pretty large" can you further explain it to
me? also thank you for responding i appreciate your service.

sincerely,
whemiko

**Comment by JavkhlanK** [comment]
Literally that it's large. Too large. Try to open the file I mentioned, then you'll see what I meant.

**Comment by mikothedev** [comment]
i already did, and there's nothing wrong with the source code it's working
but suddenly it doesn't I don't know why

**Comment by JavkhlanK** [comment]
The compiler doesn't lie. Fix your code.

**Comment by mikothedev** [comment]
well it does lmao i analyze every single line of code you wanna know what i
found? the sketchware applications bug it doesn't accept a huge line amount
of code in add code source directly and i tried my code in other IDE and it
works flawlessly lol turns out it's not my code

**Comment by JavkhlanK** [comment]
That's still not the compiler's fault. Anyway, please stop getting off-topic.

**Comment by mikothedev** [comment]
I'm not getting off the topic it's literally the same topic "compiler" and
if it's not compilers fault then it's the application fault.

**Comment by JavkhlanK** [comment]
This' topic is the TooLargeTransaction exception, nothing else. Whatever issue you're having is the cause of it.

While not being able to paste, I don't know, 10k characters of code into a Block might be a bug, that's not how you're supposed to use the app. It's mostly focused on not too many Blocks in an Event with every single one not having too much code.

Anyway since your tone's too annoying to work with, I'll leave it at this.

**Comment by mikothedev** [comment]
you're too annoying too you started it I'm just asking for guidance but nah
you started an argument, I'm asking nicely
