### ISSUE TITLE
New Update Request 

### ISSUE THREAD

**Issue by SkeeterGH** [Sketchware-Pro/Sketchware-Pro#1083]
When should we be expecting new release

**Comment by SkeeterGH** [comment]
When should we be expecting new version

**Comment by JavkhlanK** [comment]
You can't know since we can't know. No one can with Sketchware Pro.

**Comment by ilyassesalama** [comment]
Sketchware Pro isn't ours to sell since it's a mod as mentioned in [the disclaimer](https://github.com/Sketchware-Pro/Sketchware-Pro?tab=readme-ov-file#disclaimer). Even if it's ours, the team behind Sketchware Pro would probably not be happy to sell it as they're huge fans of open-source projects. My suggestion is, if you have money, either invest it in a freelancer who's willing to make your ideas come true or why not donate to the modders behind this project? Even though we're not asking for money.
