### ISSUE TITLE
Upgrade Compile Dialog

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1149]
I just thought it would be cool if using the ```material redesign```, the Sketchware Pro compile Dialog could be completely revamped to make the app feel more professional. 

Update this ↓
![Screenshot_20240602_090604_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/34af88b4-75f1-4645-ad7b-065e80ebb029)

**Comment by ilyassesalama** [comment]
I tried to redesign it, but didn't continue because I had no idea for a good design. It's not about making it rely on M3, but it's more of making something unique.

**Comment by guhg** [comment]
> I tried to redesign it, but didn't continue because I had no idea for a good design. It's not about making it rely on M3, but it's more of making something unique.

Just make it a Material Dialog that says Compiling as the title and make the message show what's happening (ex. linking Resources with AAPT2...)

**Comment by guhg** [comment]
It doesn't have to be super unique

**Comment by HehehBoiii78** [comment]
Just joining this discussion, because I have (I think this idea may be good) a good idea. Set "Building project" as the M3 dialog's title and use clickable outlined M3 cards for the "true" or "false" buttons. Put a full M3 divider between the title and the Question/Answer area, and another divider at the bottom of the clickable cards, and add a textview below the second divider using the color "?colorOnSurfaceVariant" to make it look like an M3 dialog's message, and make the textview display the build messages (i.e., "Deleting temporary files", "Compiling resources with AAPT2", etc.). On the left side of the textview put an M3 circular indeterminate progress indicator.
I hope this is a good design 😅

**Comment by HehehBoiii78** [comment]
Just joining this discussion, because I have (I think this idea may be good) a good idea. Set "Building project" as the M3 dialog's title and use clickable outlined M3 cards for the "true" or "false" buttons. Put a full M3 divider between the title and the Question/Answer area, and another divider at the bottom of the clickable cards, and add a textview below the second divider using the color "?colorOnSurfaceVariant" to make it look like an M3 dialog's message, and make the textview display the build messages (i.e., "Deleting temporary files", "Compiling resources with AAPT2", etc.). On the left side of the textview put an M3 circular indeterminate progress indicator.
I hope this is a good design 😅
