### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by PINTUSINGH8** [Sketchware-Pro/Sketchware-Pro#284]
Source Code Not Build In Aide

**Comment by khaled-0** [comment]
We don't really care.
It's not Sketchware Pro's problem.

Invalid, Close this

**Comment by JavkhlanK** [comment]
That's probably because AIDE doesn't support compiling Java 1.8 code. Sketchware Pro's sources do have Java 1.8 code though, so you will have to upgrade your build tools to build sources.

By the way, you can build Sketchware Pro's sources with Sketchware Pro itself! Main modder Hasrat made a tutorial on that, [here's it on YouTube](https://youtu.be/lsqShiSh2uU)
