### ISSUE TITLE
Declare attribute "android:exported" for Android 12 

### ISSUE THREAD

**Issue by franciscowilton** [Sketchware-Pro/Sketchware-Pro#307]
Error in Google Play Console:

You uploaded an APK or Android App Bundle that has an activity, activity alias, service, or broadcast receiver with an intent filter, but without the `android:exported` property set.  The file cannot be installed on Android 12 or newer.  Go to: https://developer.android.com/about/versions/12/behavior-changes-12#exported

I don't know if I understood correctly, should I add this attribute to activities as well? Like for example:

		 <activity
			android:name="com.google.android.gms.ads.AdActivity"
			android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
			android:theme="@android:style/Theme.Translucent" 
                    android:exported="false" />

**Comment by ryanfaiz** [comment]
After reading this article
https://developer.android.com/about/versions/12/behavior-changes-12#exported
I think the android:exported must be declared explicitly with "true" or "false"

I had the same issue when using Sketchware Pro v6.4.0-rc01. Since "Direct Code Editor" had been removed in this version, I tried to change the AndroidManifest.xml file in the source code using file editor, and when I tried to export the project, the AndroidManifest.xml file always came back to the previous version (which the android:exported not insert yet). 
Fortunately, the v6.4.0-beta.6 version still rolled out in Github, so my temporal solution is:

1. Backup my project to a different folder
2. Uninstall v6.4.0-rc01 version
3. Install v6.4.0-beta.6 version
4. Restore my project using a backup file (usually projectname.swb)
5. Open my project
6. Click the three dots button on the right top corner
7. Scroll down and click "Direct Code Editor"
8. Click AndroidManifest.xml in the center top
9. Add android:exported tag
10. Click "save"  and "Apply Changes"
11. Then you can export your project and upload it to Google Play Console

**Comment by roukean** [comment]
you can just add this code with command blocks, you don't need to download anything.

**Comment by franciscowilton** [comment]
> you can just add this code with command blocks, you don't need to download anything.

That's exactly what I did, I just want to know if I did it right.

**Comment by JavkhlanK** [comment]
You have to add that attribute to all `<activity>` tags too. Sketchware Pro doesn't add them by default though, so that should be fixed.

**Comment by franciscowilton** [comment]
> 

Right, thanks.

**Comment by JavkhlanK** [comment]
Keeping this Issue opened until it gets fixed by Sketchware Pro.

**Comment by hasrat-ali** [comment]
Done with 6.4.0-rc2

**Comment by JavkhlanK** [comment]
Completed fully (for projects using OneSignal) with 661780f639219932035188b1257204e09a32ad28, will be released with v6.4.0-rc03.
