### ISSUE TITLE
ViewPager setFragmentAdapter Block not working

### ISSUE THREAD

**Issue by nikhilsingraha** [Sketchware-Pro/Sketchware-Pro#355]
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/620/app/src/main/java/com/uptime/store/HomeActivity.java (at line 82)
	f.setTabCount(2);
	  ^^^^^^^^^^^
The method setTabCount(int) is undefined for the type FragmentStatePagerAdapter
----------
1 problem (1 error)

**Comment by JavkhlanK** [comment]
Please don't spam creating Issues / Discussions if you have questions the next time.

That's a currently known Sketchware Pro v6.4.0-rc01 / v6.4.0-rc01-kt issue, and you can't really do anything except for using own code instead of the ViewPager setFragmentAdapter Block. If you need that Block working, use an earlier Sketchware Pro version (e.g. v6.3.0 fix1).

**Comment by JavkhlanK** [comment]
This bug got fixed already, but this Issue stays open until v6.4.0-rc02 gets released.

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
