### ISSUE TITLE
Google PlayStore Native Debug Symbol / problem with native libs 

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#379]
Google PlayStore Native Libs  Problem. 

Apk working fine...aab also Working fine( i tested with 3rd-party aab2apk builder)...but when aab uploaded at PlayStore then its decreased apk size 

(with libs(.so) 12MB.... To..... without libs size is 5MB)

and Doesn't contains libs folder (.so) files...that means (.so) files missing😒

PlayStore warming that : my app contains native libs and so i have to upload Native Debug symbol and mapping

#help

**Comment by JavkhlanK** [comment]
How can the AAB still be fine without Native libraries if they'd be missing? Anyway, I think you didn't look in the correct AAB path, in currently generated AAB's Native libraries are stored in base/libs/&lt;arch&gt;/.

About the debug symbols: Since you provide the .so file yourself, Sketchware Pro can't just create those, they were made alongside the .so file. If you could provide such a file, I could try to look into including them in AAB's.

**Comment by AndroXStudiO** [comment]
Under AAB path base/libs/<arch>/.so   
files available.
And its working fine. I tested this aab using aab2apk converter. 
But problem with GooglePlaySyore after upload that aab to GooglePlay, automatic its decrease 
apk size and automatic missing libs(.so) files.

But playStore show me that "my app contain native codes" but native are missing when download apk from playStore.

**Comment by JavkhlanK** [comment]
Wait, that's weird. I'm not sure what to do though, it kinda looks like it's a bug in Google Play.

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this. This just sounds like you didn't add Native libraries for all architectures, or even put them into the wrong architecture folder. If you still have this issue, please re-open this and upload the .aab file that's causing the issue. An .apks file or all .apk files generated by Google Play for every device type the app's available for, especially those with missing Native libraries would also be very helpful.
