### ISSUE TITLE
Youtube Player

### ISSUE THREAD

**Issue by whazza1983** [Sketchware-Pro/Sketchware-Pro#401]
Hello the youtube player is not working.
My app keeps crashing

**Comment by JavkhlanK** [comment]
We're aware of that bug, but aren't really sure why that's happening.

To get to the details, the APK is crashing due to the application class not getting found somehow. Opening the APK's DEX files with e.g. MT Manager shows that the classes are there though. That's as far as I've analyzed that problem so far.

**Comment by AlQutby** [comment]
كيف استطيع التواصل مع مطورين سيكتشوير برو؟

في الاثنين، 16 ماي 2022 10:53 م Javkhlan K. ***@***.***> كتب:

**Comment by JavkhlanK** [comment]
@AlQutby, if you want to contact the "developers" of Sketchware Pro, use this GitHub repository, or join the official Discord server and ask in, for example, the channel #general.

**Comment by AlQutby** [comment]
لدي اقتراحات مهمة داخل سيكتشوير وضرورية لاي مطور اريد اقتراحها لهمSent from my Verizon, Samsung Galaxy smartphone
-------- الرسالة الأصلية --------من: "Javkhlan K." ***@***.***> التاريخ: 16‏/5‏/2022  11:03 م  (GMT+03:00) إلى: Sketchware-Pro/Sketchware-Pro ***@***.***> نسخة: AlQutby ***@***.***>, Mention ***@***.***> الموضوع: Re: [Sketchware-Pro/Sketchware-Pro] Youtube Player (Issue #401) 
@AlQutby, if you want to contact the "developers" of Sketchware Pro, use this GitHub repository, or join the official Discord server and ask in, for example, the channel #general.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Sketchware-Pro/Sketchware-Pro/issues/401#issuecomment-1128081529",
"url": "https://github.com/Sketchware-Pro/Sketchware-Pro/issues/401#issuecomment-1128081529",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by User0790** [comment]
YoutubePlayerView works great in sketchware v6.4.0 beta 6
https://drive.google.com/file/d/17XcClWxXTnFmN0q3jaC7ddNdK18Zwosg/view?usp=drivesdk

**Comment by User0790** [comment]
![Screenshot_2023-01-10-23-11-28-393_player normal np](https://user-images.githubusercontent.com/84449911/211653583-17942d22-a6f8-4f58-b661-b4b05ffdeeef.jpg)


The player worked when I removed the cloned classes from the compiled apk, the error is due to the fact that the latest version of the sketchware clones the classes in the library for youtubeVideoPlayer ....
