### ISSUE TITLE
How to solve the GDPR message?

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#902]
How to solve the GDPR message?

**Comment by JavkhlanK** [comment]
I have no clue what you're talking about. When creating an Issue, *always* make sure to give enough details *in the initial Issue description alone* so that *anyone* can understand what you mean and, if possible, reproduce the issue you're having *without having to ask for further information*.

Anyway that doesn't seem like a Sketchware Pro bug or anything that's directly caused by the app. This isn't a general-purpose Sketchware (Pro) help forum.

**Comment by JavkhlanK** [comment]
Please re-open only if you are **sure** it's directly caused by Sketchware Pro **and** you can report much more details than just "GDPR message".
